apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-pod
  template:
    metadata:
      labels:
        app: nginx-pod
    spec:
      containers:
        - name: nginx-pod
          image: nginx
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  # type: NodePort
  selector:
    app: nginx-pod
  ports:
    - port: 80
      targetPort: 80
      # nodePort: 30000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ing
  labels:
    name: nginx-ing
spec:
  ingressClassName: nginx
  rules:
    - host: test.local
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: nginx-svc
                port:
                  number: 80