apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
  - image: nginx:latest
    name: nginx
    resources: {}
    envFrom:
      - configMapRef:
          name: nginx-cm
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}