apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-dep
  labels: 
    app: nginx-dep

spec:
  template: 
    metadata: 
      name: nginx-pod
      labels: 
        env: demo
        app: nginx-pod
        role: reverse-proxy
        type: frontend
    spec:
      containers:
        - image: nginx
          name: nginx
  replicas: 3
  selector:
    matchLabels:
      type: frontend