apiVersion: v1
kind: Service
metadata:
  name: nginx-clusterip-service
  labels:
    type: service
spec:
  type: ClusterIP
  ports: 
    - port: 80
      targetPort: 80
  selector:
      env: demo
      app: nginx-pod