apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport-service
  labels:
    type: service
spec:
  type: NodePort
  ports: 
    - port: 80
      targetPort: 80
      nodePort: 30001
  selector:
      env: demo
      app: nginx-pod